export const CHARACTER_BIBLE_SCHEMA = {
  type: "object",
  properties: {
    name: { type: "string" },
    gender: { type: "string" },
    height: { type: "string" },
    physique: { type: "string" },
    hairStyle: { type: "string" },
    hairColor: { type: "string" },
    skinTone: { type: "string" },
    faceShape: { type: "string" },
    eyes: { type: "string" },
    nose: { type: "string" },
    mouth: { type: "string" },
    ears: { type: "string" },
    eyebrows: { type: "string" },
    distinguishingFeatures: { type: "string" },
    clothing: { type: "string" },
    belongings: { type: "string" },
    referenceAge: { type: "string" },
  },
  required: [
    "name",
    "gender",
    "height",
    "physique",
    "hairStyle",
    "hairColor",
    "skinTone",
    "faceShape",
    "eyes",
    "nose",
    "mouth",
    "ears",
    "eyebrows",
    "distinguishingFeatures",
    "clothing",
    "belongings",
    "referenceAge",
  ],
  additionalProperties: false,
} as const;
